### ISSUE TITLE
Major security breach

### ISSUE THREAD

**Issue by FlorianGuerrier** [larafale/mangopay#82]
**Mangopay a repéré une faille majeure de sécurité.** En utilisant cette librairie, les utilisateurs finaux (payeurs/contributeurs/acheteurs) valident le formulaire de paiement dans lequel ils saisissent leurs données sensibles de cartes sur votre site; **celles-ci passent par votre serveur** pour être ensuite envoyées sur le serveur PSP (côté Mangopay). Cela représente une grave faille règlementaire et une violation des règles PCI DSS. Il faut obligatoirement que les données de cartes soient envoyées directement sur le serveur PSP. 

Sans correctif de cette _issue_, MANGOPAY informe les plateformes utilisant cette librairie qu'elles doivent impérativement se mettre en conformité en utilisant par exemple la librairie officielle MANGOPAY : https://github.com/Mangopay/mangopay2-nodejs-sdk.

---

**Mangopay has spotted a major security breach.** By using this library, end customers (payers / contributors / buyers) validate the form in which they enter their sensitive card details on your site; these **pass through your server** to be sent to the PSP server (Mangopay side). This represents a serious regulatory breach and a violation of PCI DSS rules. It is mandatory that the card details are sent directly to the PSP server.

Without any correction for this _issue_, MANGOPAY informs the platforms using this library that they **must imperatively get in compliance** using for example the official bookstore MANGOPAY: https://github.com/Mangopay/mangopay2-nodejs-sdk.

**Comment by godspeedelbow** [comment]
Can you be more specific as to where this happens?

**Comment by godspeedelbow** [comment]
And feel free to advice your customers to use whichever library. This is an open source project – nobody is forced to use it.

**Comment by larafale** [comment]
This has nothing to do with a security breach. In order to be PCI compliant a merchant should not send card details to his own server. In order to do this he can use the 2 steps registration process using `card.initRegistration()` method followed by `card. sendCardDetails()`. which is considered a good practice.

But nothing prevent the developper from sending the card details back to his server (whatever the reason is). So it's always the developper who decide if he is compliant or not, not the the library. You could be non compliant even with the official mango client. The 1 step process `card.create()` is a wrapper around those 2 methods above, nothing more. So please stop the bullshit. We have been in touch before and you did not give a fuck. so now fuck off, we are grown devs, thank you !! and happy new year
